#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale ~/Downloads/wall.jpg
#polybar shadobar --config=~/polybar/config &
#youtube-music-bin &
picom --config ~/picom.conf --experimental-backends -b

bspc monitor -d 一 二 三 四 五 六 七 八 九 十
bspc monitor HDMI2 -d 1 2 3 4 5 6 7 8 9

bspc config focused_border_color '#E84F4F'
bspc config normal_border_color "#000000"

bspc config border_width        0
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
bspc rule -a st-256color state=floating
bspc rule -a myWindow state=floating
bspc rule -a win0 state=floating
bspc rule -a "YouTube Music" desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
